version: '3.7'

services:
  mysql:
    image: mysql:8.0.31
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'camera'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      command: |
        mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root']
      timeout: 5s
      retries: 10
    networks:
      - backend

  camera-backend:
    restart: always
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8090:8000
    networks:
      - backend
volumes:
  mysql-data:

networks:
  backend:
    driver: 'bridge'

  # camera-be:
  #   restart: always
  # build:
  #   context: .
  #   dockerfile: ./Dockerfile
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - mysql
  #   networks:
  #     - backend
  #   ports:
  #     - '8090:3000'
  #   entrypoint: ['./wait-for-it.sh', 'mysql:3306', '--', 'npm', 'start']
