apiVersion: batch/v1
kind: Job
metadata:
  name: migrations-database-$CI_PROJECT_NAME
  namespace: devops-cloud
spec:
  template:
    spec:
      containers:
        - command:
            - yarn
            - typeorm:run-migrations
          name: migrations-database-$CI_PROJECT_NAME
          envFrom:
            - configMapRef:
                name: $CI_PROJECT_NAME
                optional: false
          image: nexus.api-connect.io/$CI_PROJECT_NAME:$IMAGE_TAG
          imagePullPolicy: Always
      imagePullSecrets:
        - name: nexus
      restartPolicy: Never

