stages:
    - prepare env
    - build
    - update Migrations
    - deploy

variables:
  SET_KUBECONFIG: $PROD_KUBECONFIG
  PATH_ENV_FILE: $ENV_FILE_PROD
  PATH_DOCKER_BUILD_ENV_FILE: $DOCKER_BUILD_ENV_FILE_PROD

  IMAGE_REGISTRY_USER: $NEXUS_REPO_USER
  IMAGE_REGISTRY_PASS: $NEXUS_REPO_PASSWORD
  IMAGE_REGISTRY_URL: $IMAGE_REGISTRY_URL

  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  PROJECT_NAME: $CI_PROJECT_NAME
  NAMESPACE: $CI_PROJECT_ROOT_NAMESPACE
  IMAGE_NAME_BUILD: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH:$IMAGE_TAG
  IMAGE_NAME_BUILD_LATEST: $CI_PROJECT_NAME-$CI_COMMIT_BRANCH:latest


prepare env:
  stage: prepare env
  only:
      - prod
  image: alpine/k8s:1.23.16
  tags:
    - devops-cloud-prod
  script:
    - export $(cat $PATH_DOCKER_BUILD_ENV_FILE | xargs)
    - envsubst < Dockerfile > Dockerfile-Build
  artifacts:
    paths:
      - Dockerfile-Build


build:
  stage: build
  tags:
    - devops-cloud-prod
  only:
    - prod
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo $IMAGE_REGISTRY_URL
    - echo $IMAGE_REGISTRY_USER
    - echo $IMAGE_REGISTRY_PASS
    - echo "{\"auths\":{\"$IMAGE_REGISTRY_URL\":{\"auth\":\"$(printf "%s:%s" "$IMAGE_REGISTRY_USER" "$IMAGE_REGISTRY_PASS" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
    - cat Dockerfile-Build
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile-Build"
      --cache=true
      --destination "$IMAGE_REGISTRY_URL/$IMAGE_NAME_BUILD"
      --destination "$IMAGE_REGISTRY_URL/$IMAGE_NAME_BUILD_LATEST"

update Migrations:
  stage: update Migrations
  tags:
    - devops-cloud-prod
  only:
    - prod
  image: alpine/k8s:1.23.16
  variables:
        IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  script: |
    sh deployment/k8s-deployment/$CI_COMMIT_BRANCH/deploy-job.sh

deploy:
  tags:
    - devops-cloud-prod
  stage: deploy
  only:
    - prod
  image: alpine/k8s:1.23.16
  variables:

  script: |
    sh deployment/k8s-deployment/$CI_COMMIT_BRANCH/deploy.sh
